function about() {
    const div = document.createElement("div");
    const h2 = document.createElement("h2");
    const h3 = document.createElement("h3");
    const p1 = document.createElement("p");
    const p2 = document.createElement("p");
    const div1 = document.createElement("div");
    const div11 = document.createElement("div");
    const div2 = document.createElement("div");
    const div21 = document.createElement("div");
    const p3 = document.createElement("p");
    const p4 = document.createElement("p");
    const p5 = document.createElement("p");
    const p6 = document.createElement("p");
    const iframe = document.createElement("iframe");
    const h4 = document.createElement("h3");
    iframe.src = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3884.4488642381375!2d79.06438979999997!3d13.197111800000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bad5dcb4a93efff%3A0xc50ecf2b80fd0a96!2sCaf%C3%A9%20Coffee%20Day!5e0!3m2!1sen!2sin!4v1677247556291!5m2!1sen!2sin";
    iframe.style = "height: auto; width: 40%;";
    p6.textContent = " Everyday from 10am - 11pm";
    p5.textContent = "1234567890";
    p4.textContent = "restaurant212323@gmail.com";
    h4.textContent = "contact";
    div21.appendChild(h4);
    div21.appendChild(p4);
    div21.appendChild(p5);
    div21.appendChild(p6);
    div2.appendChild(div21);
    div21.style = "width:60%;word-break: break-all;";
    iframe.style = "width:40%;";
    div2.appendChild(iframe);
    div2.style = "display: flex; width:100%;";
    p3.textContent = "At our restaurant, we believe that great food should be accompanied by exceptional service and a warm, inviting atmosphere. Our knowledgeable staff are passionate about food and are always on hand to provide recommendations and ensure that your dining experience is as enjoyable as possible. Whether you are looking for a romantic dinner for two, a family meal, or a special occasion, we are dedicated to providing you with an unforgettable dining experience that will keep you coming back for more. So why not join us today and discover the delights of our restaurant for yourself";
    p2.textContent = "Welcome to our restaurant, where we strive to provide our customers with an unforgettable dining experience. Our menu features a wide range of delicious dishes, prepared with the freshest ingredients and cooked to perfection. We specialize in [insert type of cuisine], but also offer a variety of options to suit all tastes and dietary requirements.";
    const img1 = document.createElement("img");
    const img2 = document.createElement("img");
    const img3 = document.createElement("img");
    img3.src = "https://raw.githubusercontent.com/Reddyveerendra/Restaurant-Page/main/images/chef.jpg";
    img3.style = "height: 200px; width: 100%;";
    img2.style = "height: 200px; width: 100%;";
    img2.src = "https://raw.githubusercontent.com/Reddyveerendra/Restaurant-Page/main/images/dishes.jpg";
    div11.appendChild(img2);
    div11.appendChild(img3);
    div11.style = "display: grid; grid-template-rows: 1fr 1fr;";
    img1.src = "https://raw.githubusercontent.com/Reddyveerendra/Restaurant-Page/main/images/interior.jpg";
    img1.style = "height: 400px; width: 100%;";
    div1.appendChild(img1);
    div1.appendChild(div11);
    div1.style = "display: grid; grid-template-columns: 1fr 1fr;";
    p1.textContent = "Looking for a delicious dining experience in a comfortable and welcoming atmosphere? Look no further than our restaurant! Our menu features a wide variety of dishes, ranging from classic comfort foods to unique and flavorful creations that are sure to satisfy any palate. All of our dishes are made with fresh, high-quality ingredients, and we take pride in offering a dining experience that is both delicious and affordable. Whether you're looking for a romantic night out, a family dinner, or a casual lunch with friends, our restaurant is the perfect destination.";
    h3.textContent = "Why Choose Us?";
    h2.textContent = 'About Us';
    h2.style = "text-align: center;";
    div.style = "border: 1px solid black; display: flex; flex-direction: column; padding: 5% 18%; justify-content: center; gap: 20px;";
    div.appendChild(h2);
    div.appendChild(h3);
    div.appendChild(p1);
    div.appendChild(div1);
    div.appendChild(p2);
    div.appendChild(p3);
    div.appendChild(div2);
    return div;

}
export { about };